### ISSUE TITLE
The example `SMA Crossover Strategy` failed

### ISSUE THREAD

**Issue by bigtan** [pmorissette/bt#48]
The example `SMA Crossover Strategy` in the document failed, and the error log is below:

```
AttributeError: 'Series' object has no attribute 'items'
```

I Think this is because the `WeighTarget` does not assign an `dict` to `target.temp['weights']`, so I just repacle `target.temp['weights'] = w.dropna()` with `{w.index[i]:w.values[i] for i in range(len(w.index))}` maybe there will be a better way.

**Comment by pmorissette** [comment]
Hey @bigtan,

What is your bt, pandas and numpy version? I just ran the code and it works fine on my end.

If it isn't too much trouble, could you please paste the code you ran so that I can make sure we are indeed looking at the same thing?

Thanks,
Phil

**Comment by testforvln** [comment]
Hi @pmorissette , I've come across the same problem when I tried example SMA Crossover Strategy.

I setup bt with Anaconda Scientific Python Distribution 2.3.0 and pip. My tool version is shown blow:
python: 2.7
bt: 0.1.10
pandas: 0.16.2
numpy: 1.9.2

Could you please help me with this problem?

Thanks

**Comment by pmorissette** [comment]
Hey @testforvln 

Can you paste the code you are using please?

Cheers,
Phil

**Comment by testforvln** [comment]
Just the same as the documents from http://pmorissette.github.io/bt/examples.html#sma-crossover-strategy

Here's the code:

import bt
%matplotlib inline

# download data
data = bt.get('aapl, msft, c, gs, ge', start = '2010-01-01')

# calculate moving average DataFrame using pandas' rolling _mean
import pandas as pd
# a rolling mean is a moving average
sma = pd.rolling_mean(data, 50)

# let's  see what the data looks like - this is by no means a pretty chart, but it does the job
plot = bt.merge(data, sma).plot(figsize=(15, 5))

class SelectWhere(bt.Algo):
    """
    Selects securities based on an indicator DataFrame.
    Selects securities where the value is True on the current date (target.now)
    Args:
            * signal (DataFrame): DataFrame containing the signal (boolean DataFrame)
    Sets:
            * selected
    """
    def __init__(self, signal):
        self.signal = signal
        
    def __call__(self, target):
        # get signal on target.now
        if target.now in self.signal.index:
            sig = self.signal.ix[target.now]
            
            # get indices  where true as list
            selected = list(sig.index[sig])
            
            # save in temp - this will be used by the weighing algo
            target.temp['selected'] = selected
        
        # return True because we want to keep on moving down the stack
        return True


# first we create the Strategy
s = bt.Strategy('above50sma', [SelectWhere(data > sma),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])

# now we create the Backtest
t = bt.Backtest(s, data)

# and let's run it!
res = bt.run(t)

res.display()

def above_sma(tickers, sma_per = 50, start = '2010-01-01', name = 'above_sma'):
    """
    Long securities that are above their n period
    Simple Moving Average with equal weighs,
    """
    # download data
    data = bt.get(tickers, start = start)
    sma = pd.rolling_mean(data, sma_per)
    
    # crteate strategy
    s = bt.Strategy(name, [SelectWhere(data > sma),
                            bt.algos.WeighEqually(),
                            bt.algos.Rebalance()])
        
    # now we create the backtest
    return bt.Backtest(s, data)

# simple backtest to test long-only allocation
def long_only_ew(tickers, start = '2010-01-01', name = 'long_only_ew'):
    s = bt.Strategy(name, [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])
    data = bt.get(tickers, start = start)
    return bt.Backtest(s, data)

# create the backtest
tickers = 'aapl, msft, c, gs, ge'
sma10 = above_sma(tickers, sma_per = 10, name = 'sma10')
sma20 = above_sma(tickers, sma_per = 20, name = 'sma20')
sma40 = above_sma(tickers, sma_per = 40, name = 'sma40')
benchmark = long_only_ew('spy', name = 'spy')

# run all the backtest
res2 = bt.run(sma10, sma20, sma40, benchmark)

res2.plot()

res2.display()

class WeighTarget(bt.Algo):
    """
    Sets target weights based on a target weight DataFrame.
    Args:
        * target_weighs(DataFrame): DataFrame containing the target weights
    Sets:
        * weights
    """
    def __init__(self, target_weights):
        self.tw = target_weights
    
    def __call__(self, target):
        # get target weights on data target.now
        if target.now in self.tw.index:
            w = self.tw.ix[target.now]
            
            # save in temp - this will be used by the weighing algo
            # also dropping any na's just in case they pop up 
            target.temp['weights'] = w.dropna()
            
            
        # return True because we want to keep on moving down the stack 
        return True


## download some data & calc SMAs
data = bt.get('spy', start = '2010-01-01')
sma50 = pd.rolling_mean(data, 50)
sma200 = pd.rolling_mean(data, 200)

## now we need to calculate our target weight DataFrame
# first we will copy the sma200 DataFrame since our weights will have the same structure
tw = sma200.copy()
tw[sma50 > sma200] = 1.0
tw[sma50 <= sma200] = -1.0
# here we will set the weigh to 0 - this is because the sma200 needs 200 data points before
# calculating its first point, Therefore, it will start with a bunch of nulls(NaNs).
tw[sma200.isnull()] = 0.0

# plot the target weights + chart of price & SMAs
tmp = bt.merge(tw, data, sma50, sma200)
tmp.columns = ['tw', 'price', 'sma50', 'sma200']
ax = tmp.plot(figsize = (15, 5), secondary_y = ['tw'])

ma_cross = bt.Strategy('ma_cross', [WeighTarget(tw),
                                    bt.algos.Rebalance()])
t = bt.Backtest(ma_cross, data)
res = bt.run(t)

**Comment by testforvln** [comment]
Just the same as documents from http://pmorissette.github.io/bt/examples.html#sma-crossover-strategy

Here's the code:

import bt
%matplotlib inline

data = bt.get('aapl, msft, c, gs, ge', start = '2010-01-01')

import pandas as pd
sma = pd.rolling_mean(data, 50)

plot = bt.merge(data, sma).plot(figsize=(15, 5))

class SelectWhere(bt.Algo):
    def __init__(self, signal):
        self.signal = signal
        
    def __call__(self, target):
        if target.now in self.signal.index:
            sig = self.signal.ix[target.now]
            
            selected = list(sig.index[sig])
            
            target.temp['selected'] = selected
        
        return True


s = bt.Strategy('above50sma', [SelectWhere(data > sma),
                               bt.algos.WeighEqually(),
                               bt.algos.Rebalance()])

t = bt.Backtest(s, data)

res = bt.run(t)

res.display()

def above_sma(tickers, sma_per = 50, start = '2010-01-01', name = 'above_sma'):
    data = bt.get(tickers, start = start)
    sma = pd.rolling_mean(data, sma_per)
    
    s = bt.Strategy(name, [SelectWhere(data > sma),
                            bt.algos.WeighEqually(),
                            bt.algos.Rebalance()])
        
    return bt.Backtest(s, data)

def long_only_ew(tickers, start = '2010-01-01', name = 'long_only_ew'):
    s = bt.Strategy(name, [bt.algos.RunOnce(),
                           bt.algos.SelectAll(),
                           bt.algos.WeighEqually(),
                           bt.algos.Rebalance()])
    data = bt.get(tickers, start = start)
    return bt.Backtest(s, data)

tickers = 'aapl, msft, c, gs, ge'
sma10 = above_sma(tickers, sma_per = 10, name = 'sma10')
sma20 = above_sma(tickers, sma_per = 20, name = 'sma20')
sma40 = above_sma(tickers, sma_per = 40, name = 'sma40')
benchmark = long_only_ew('spy', name = 'spy')

res2 = bt.run(sma10, sma20, sma40, benchmark)

res2.plot()

res2.display()

class WeighTarget(bt.Algo):
    def __init__(self, target_weights):
        self.tw = target_weights
    
    def __call__(self, target):
        if target.now in self.tw.index:
            w = self.tw.ix[target.now]
            
            target.temp['weights'] = w.dropna()
            
        return True


data = bt.get('spy', start = '2010-01-01')
sma50 = pd.rolling_mean(data, 50)
sma200 = pd.rolling_mean(data, 200)

tw = sma200.copy()
tw[sma50 > sma200] = 1.0
tw[sma50 <= sma200] = -1.0
tw[sma200.isnull()] = 0.0

tmp = bt.merge(tw, data, sma50, sma200)
tmp.columns = ['tw', 'price', 'sma50', 'sma200']
ax = tmp.plot(figsize = (15, 5), secondary_y = ['tw'])

ma_cross = bt.Strategy('ma_cross', [WeighTarget(tw),
                                    bt.algos.Rebalance()])
t = bt.Backtest(ma_cross, data)
res = bt.run(t)

**Comment by testforvln** [comment]
Hi @pmorissette , I saw this commit on bt between 0.1.10 and 0.1.11:
https://github.com/pmorissette/bt/commit/3fd5e2692779150ec6ce32cb989b79219041811b
Since I used pip to install bt, the installed version remains at 0.1.10. Would you like it to be upgraded to the newest version?

Thanks

**Comment by jeffereylj** [comment]
Hi @pmorissette, I really like your BT. The design is very straightfoward. But I am experiencing the same problem as @testforvln has reported. I am using the latest Anaconda.( just downloaded it an installed it). Could you please reply and fix it?

**Comment by pmorissette** [comment]
Hey all,

Sorry for the slow response on this issue. I'll try to get this done ASAP.

Cheers,
Phil

**Comment by bigtan** [comment]
@pmorissette the Source code in pypi is not the latest. maybe this is the reason

**Comment by pmorissette** [comment]
Hey @bigtan - just looking at this as we speak. I'll report back shortly. 

Thanks,
Phil

**Comment by pmorissette** [comment]
Hey @bigtan, @jeffereylj, @testforvln.

First off, sorry for keeping you waiting so long. I've just updated the code on PyPI. @bigtan was right, the issue was simply that the code on PyPI (pip repository) was out of sync with the code in this repo. When I added support for Python 3, I forgot to push out the update to PyPI.

Please let me know if you still have issues once you've ran the following command:

```
pip install --upgrade bt
```

Then try the same code again.

Thanks for your patience,
Phil

**Comment by jeffereylj** [comment]
Thanks a lot, @pmorissette .  I will test it tonight and report back to you!

**Comment by jeffereylj** [comment]
i upgraded bt and still have some errors. It seems to be related to scipy. which version of scipy does bt require?

**Comment by pmorissette** [comment]
Hey @jeffereylj,

```bt``` requires ``ffn``, which in turn requires ```scipy``` although I don't think I specified a version, so it will probably install the latest version. 

What's the error message?

**Comment by jeffereylj** [comment]
Hey @pmorissette , thanks a lot for your quick reply. I have re-installed python and it works fine now.

sorry for the inconvenience.

**Comment by pmorissette** [comment]
Hey @jeffereylj  - no worries! Glad it works.

Cheers,
Phil
